title: Calxus Blog
description: Calxus' personal blog to document the mischief of a DevSecOps Engineer 
permalink: ':title/'
baseurl: ""
url: "https://oniontuga.github.io"


author: Calxus
author-img: calxus.png # add your photo
about-author: DevOps Engineer with a penchant for pentesting and proud owner of an over-engineered home network
social-twitter: TheCalxus
social-github: calxus
social-email: calxus@protonmail.ch

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
