title: OnionTuga
description: A blog for cyber, tech and random stuff
permalink: ':title/'
baseurl: ""
url: "https://oniontuga.github.io"


author: OnionTuga 
author-img: onion.jpg # add your photo
about-author: Cyber, and foss ENTHUSIASTIC. Trying to escape to big tech and hosting a site in github (lol). Hack the world or some shit.
social-twitter: anon58983741
social-github: oniontuga
social-email: ubica17@pm.me

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
